name: Auto Run Togel Poster

on:
  schedule:
    - cron: '*/5 * * * *'  # jalan setiap 6 jam
  workflow_dispatch:       # bisa dijalankan manual juga

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      WP_URL: ${{ secrets.WP_URL }}
      WP_USER: ${{ secrets.WP_USER }}
      WP_APP_PASS: ${{ secrets.WP_APP_PASS }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script
      run: python run.py
